lab6/imager/accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

lab6/imager/imager/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include ('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name ='home'),
]

lab6/imager/polls/urls.py
from django.urls import path
from .import views

app_name = "polls"
urlpatterns = [

    path('',views.IndexView.as_view(), name='index'),
    path('slika/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('slika/<int:image_id>/upvote', views.upvote, name="upvote"),
    path('slika/<int:image_id>/downvote', views.downvote, name="downvote")
]

lab6/imager/accounts/models.py
from django.db import models

# Create your models here.

lab6/imager/polls/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date_published')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Comment(models.Model):
    image = models.ForeignKey(Image,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    comment = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.name

lab6/imager/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

lab6/imager/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.views import generic
from polls.models import Image
from django.urls import reverse
# Create your views here.
class IndexView(generic.ListView):
    template_name= 'polls/index.html'
    context_object_name='image_list'

    def get_queryset(self):
        return Image.objects.all

class DetailView(generic.DetailView):
    template_name ='polls/detail.html'
    model = Image

def upvote(request, image_id):
    image = get_object_or_404(Image,pk=image_id)
    image.votes +=1
    image.save()
    return HttpResponseRedirect(reverse('polls:index'))

def downvote(request, image_id):
    image = get_object_or_404(Image,pk=image_id)
    image.votes -=1
    image.save()
    return HttpResponseRedirect(reverse('polls:index'))

lab6/imager/polls/templates/polls/detail.html
<h1>{{image.name}}</h1>
<div style="width:100%">
    <div style="width:60%;float:left;"></div>
        <img src= "{{image.url}}" style="width:100%"/>

    </div>
    <div style="width: 30%;float:left;">
        <p>Score: {{image.votes}}</p>
        {% if user.is_authenticated %}
        <form action="{%url 'polls:upvote' image.id%}" method="post">
            {%csrf_token%}
        <input type= "submit" value="Vote UP!">
    </form>
    <form action="{%url 'polls:upvote' image.id%}" method="post">
        <input type= "submit" value="Vote DOWN!">
    </form>
{% endif %}
        
        
    </div>
</div>

lab6/imager/polls/templates/polls/index.html
<h1>Neki naslov aplikacije!</h1>
{% if image_list%}
    <div style="width:100%">
    {%for image in image_list%}
    <div style="width:30%; float:left;padding:10">
        <p>{{image.name}} <small>{{image.pub_date}}</small></p>
        <a href="{%url 'polls:detail' image.id %}">
        <img src= "{{image.url}}" style="width:100%" />
        </a>
    </div>
    {%endfor%}
    </div>
{%else%}
    <h3>Nema ucitanih slika</h3>
{% endif%}

lab6/imager/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

lab6/imager/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

lab6/imager/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}